name: register_tst_2025
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hexcolor: ^3.0.1
  loading_animation_widget: ^1.3.0
  page_transition: ^2.2.1
  animated_splash_screen: ^1.3.0
  lottie: ^3.2.0
  image_picker: ^1.1.2
  path_provider: ^2.0.15
  elegant_notification: ^2.5.1
  intl_phone_field: ^3.2.0
  geolocator: ^13.0.4
  permission_handler: ^11.3.0
  flutter_contacts: ^1.1.9+2
  http: ^1.3.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

dependency_overrides:
  http: 1.3.0
